### ISSUE TITLE
关于WAA-app

### ISSUE THREAD

**Issue by kct890721** [HSqure/ultralytics-pt-yolov3-vitis-ai-edge#1]
Hi @HSqure 您好～
我是之前询问您关于Vitis AI Quantize步骤的人，我的目标是将量化完的YoloV3 Demo到 ZCU102上，并要加入一些Vitis Library的IP像是您使用''pp_pipeline_accel''但在进行过程中遇到一些问题想请教您，问题如下：

1.我目前是使用Xilinx提供的Vitis AI SDimage(ZCU102)进行操作，但当我将您的repo放到FPGA上并build您repo中WAA-app的build.sh遇到了一些问题，目前猜测是Opencv版本的问题，想请问您是如何解决这个问题的？
![15593401071713](https://user-images.githubusercontent.com/86824960/154059502-862d0777-5d2e-46d5-947b-89a9c7ac395d.jpg)
2.想请问您在进行WAA-app时关于''pp_pipeline_accel''是如何产出的？方便的话可以稍微叙述一下相关步骤吗？

感谢您花费时间回答我的问题，祝新春愉快

**Comment by HSqure** [comment]
> Hi @HSqure 您好～ 我是之前询问您关于Vitis AI Quantize步骤的人，我的目标是将量化完的YoloV3 Demo到 ZCU102上，并要加入一些Vitis Library的IP像是您使用''pp_pipeline_accel''但在进行过程中遇到一些问题想请教您，问题如下：
> 
> 1.我目前是使用Xilinx提供的Vitis AI SDimage(ZCU102)进行操作，但当我将您的repo放到FPGA上并build您repo中WAA-app的build.sh遇到了一些问题，目前猜测是Opencv版本的问题，想请问您是如何解决这个问题的？ ![15593401071713](https://user-images.githubusercontent.com/86824960/154059502-862d0777-5d2e-46d5-947b-89a9c7ac395d.jpg) 2.想请问您在进行WAA-app时关于''pp_pipeline_accel''是如何产出的？方便的话可以稍微叙述一下相关步骤吗？
> 
> 感谢您花费时间回答我的问题，祝新春愉快

@kct890721 

### Q1
我是用`Vitis-AI V1.3`的`GPU docker`进行编译的,环境也都是`V1.3`, 因为`Vitis-AI V1.4`是向下兼容的, `Vitis-AI V1.4`的`opencv`版本问题可以在官方`Vitis-AI V1.4`那边的`README.md`里找一下,我记得里面有在编译里加上补丁命令来解决这个问题.

### Q2
这个在官方WAA里有详细步骤的,此外推荐参考官方文档`UG1393`

**Comment by kct890721** [comment]
> > Hi @HSqure 您好～ 我是之前询问您关于Vitis AI Quantize步骤的人，我的目标是将量化完的YoloV3 Demo到 ZCU102上，并要加入一些Vitis Library的IP像是您使用''pp_pipeline_accel''但在进行过程中遇到一些问题想请教您，问题如下：
> > 1.我目前是使用Xilinx提供的Vitis AI SDimage(ZCU102)进行操作，但当我将您的repo放到FPGA上并build您repo中WAA-app的build.sh遇到了一些问题，目前猜测是Opencv版本的问题，想请问您是如何解决这个问题的？ ![15593401071713](https://user-images.githubusercontent.com/86824960/154059502-862d0777-5d2e-46d5-947b-89a9c7ac395d.jpg) 2.想请问您在进行WAA-app时关于''pp_pipeline_accel''是如何产出的？方便的话可以稍微叙述一下相关步骤吗？
> > 感谢您花费时间回答我的问题，祝新春愉快
> 
> @kct890721
> 
> ### Q1
> 我是用V1.3的gpu docker进行编译的,环境也都是1.3的因为1.4是向下兼容的, 1.4的opencv版本问题可以在官方1.4那边的README里找一下,我记得里面有在编译里加上补丁命令来解决这个问题.
> 
> ### Q2
> 这个在官方WAA里有详细步骤的,此外推荐参考官方文档`UG1393`

Hi @HSqure 中午好
非常感谢您花时间回复我的问题
祝新春愉快

**Comment by HSqure** [comment]
> > > Hi @HSqure 您好～ 我是之前询问您关于Vitis AI Quantize步骤的人，我的目标是将量化完的YoloV3 Demo到 ZCU102上，并要加入一些Vitis Library的IP像是您使用''pp_pipeline_accel''但在进行过程中遇到一些问题想请教您，问题如下：
> > > 1.我目前是使用Xilinx提供的Vitis AI SDimage(ZCU102)进行操作，但当我将您的repo放到FPGA上并build您repo中WAA-app的build.sh遇到了一些问题，目前猜测是Opencv版本的问题，想请问您是如何解决这个问题的？ ![15593401071713](https://user-images.githubusercontent.com/86824960/154059502-862d0777-5d2e-46d5-947b-89a9c7ac395d.jpg) 2.想请问您在进行WAA-app时关于''pp_pipeline_accel''是如何产出的？方便的话可以稍微叙述一下相关步骤吗？
> > > 感谢您花费时间回答我的问题，祝新春愉快
> > 
> > 
> > @kct890721
> > ### Q1
> > 我是用V1.3的gpu docker进行编译的,环境也都是1.3的因为1.4是向下兼容的, 1.4的opencv版本问题可以在官方1.4那边的README里找一下,我记得里面有在编译里加上补丁命令来解决这个问题.
> > ### Q2
> > 这个在官方WAA里有详细步骤的,此外推荐参考官方文档`UG1393`
> 
> Hi @HSqure 中午好 非常感谢您花时间回复我的问题 祝新春愉快

@kct890721 新春愉快
